### ISSUE TITLE
Cannot find 'UIDevice' in scope

### ISSUE THREAD

**Issue by ebubekirsezer** [okta/okta-devices-swift#168]
### Describe the bug?

I added the SPM package of the okta-devices-swift in an empty project and when i run the app i am getting this error **Cannot find 'UIDevice' in scope** in OktaDeviceModelBuilder class line 135.

<img width="1144" alt="Screenshot 2023-12-12 at 10 49 24" src="https://github.com/okta/okta-devices-swift/assets/32433476/46a1cabe-7a77-41bc-b362-16ab5726b08b">

### What is expected to happen?

Class should be run without an error

### What is the actual behavior?

Giving an error to import the UIKit

### Reproduction Steps?

Adding the okta-devices-swift in an empty project and run

### SDK Version(s)

1.1.1 & 1.1.0

**Comment by moisesolmedo-okta** [comment]
This has been fixed in 1.1.2 release.
