### ISSUE TITLE
Delete Enrollment Method Error

### ISSUE THREAD

**Issue by KaannnOzdemiir** [okta/okta-devices-swift#170]
### Describe the bug?

After enrolling to Okta via iOS and when I invoke SDK's enrollment delete method, I get 401 Unauthorized error from **idp/myaccount/app-authenticators/**. 

Error details:
error="invalid_token"
error_description="The access token has been revoked."

This is happening because revoke method is invoked before **idp/myaccount/app-authenticators** endpoint in my opinion.

Some screenshots are provided below.

### What is expected to happen?

I was expecting to see delete method works properly and removed enrolments.

### What is the actual behavior?

It doesn't remove enrollments

### Reproduction Steps?

Steps:
1- Login with Okta and enroll
2- Logout and delete enrollment 
3- You should see that SDK is not removing enrollment

**Invoked endpoints and statuses during enrollment**
![enroll](https://github.com/okta/okta-devices-swift/assets/132364893/2608a8ad-da9b-4f36-8465-3992019448c6)

**Invoked endpoints and statuses during delete enrollment**
![error](https://github.com/okta/okta-devices-swift/assets/132364893/8c471845-5683-42fd-ad78-2f9a36d1ca94)

### Additional Information?

Thank you.

### SDK Version(s)

1.1.2

**Comment by IldarAbdullin-okta** [comment]
Hi @KaannnOzdemiir ,

That is totally correct assumption - `This is happening because revoke method is invoked before idp/myaccount/app-authenticators endpoint in my opinion.`

Please change the sequence of operations. Delete push authenticator enrollment first and then proceed with the sign-out process

Ildar
